"""Command-line interface for experiment validation and planning."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Any, Sequence

import yaml

from seismic_byol.experiments import (
    ConfigError,
    ResolvedRun,
    expand_experiment,
    load_experiment,
    write_run_manifests,
)


def _parse_filter(raw: str) -> tuple[str, Any]:
    if "=" not in raw:
        raise argparse.ArgumentTypeError("filters must use KEY=VALUE syntax")
    key, raw_value = raw.split("=", 1)
    if not key or not raw_value:
        raise argparse.ArgumentTypeError("filters must use non-empty KEY=VALUE syntax")
    try:
        value = yaml.safe_load(raw_value)
    except yaml.YAMLError as exc:
        raise argparse.ArgumentTypeError(f"invalid filter value: {exc}") from exc
    return key, value


def _filters(items: Sequence[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in items:
        if key in result and result[key] != value:
            raise ConfigError(f"Filter {key!r} was provided with conflicting values.")
        result[key] = value
    return result


def _format_value(value: Any) -> str:
    if isinstance(value, str):
        return value
    return json.dumps(value, sort_keys=True)


def _table(runs: Sequence[ResolvedRun]) -> str:
    if not runs:
        return "No runs match the selected filters."

    axes = sorted({axis for run in runs for axis in run.values})
    headers = ["run_id", "matrix", "stage", *axes]
    rows = [
        [
            run.run_id,
            run.matrix_name,
            run.stage,
            *[_format_value(run.values.get(axis, "-")) for axis in axes],
        ]
        for run in runs
    ]
    widths = [
        max(len(headers[index]), *(len(row[index]) for row in rows))
        for index in range(len(headers))
    ]

    def format_row(row: Sequence[str]) -> str:
        return "  ".join(value.ljust(widths[index]) for index, value in enumerate(row))

    separator = "  ".join("-" * width for width in widths)
    return "\n".join([format_row(headers), separator, *(format_row(row) for row in rows)])


def _serialize(runs: Sequence[ResolvedRun], output_format: str) -> str:
    manifests = [run.as_dict() for run in runs]
    if output_format == "json":
        return json.dumps(manifests, indent=2, sort_keys=False)
    if output_format == "yaml":
        return yaml.safe_dump(manifests, sort_keys=False)
    return _table(runs)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="seismic-byol",
        description="Validate and expand reproducible Seismic BYOL experiment matrices.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    validate = subparsers.add_parser(
        "validate", help="validate a configuration and count its runs"
    )
    validate.add_argument("config", type=Path)

    plan = subparsers.add_parser(
        "plan", help="show the concrete runs generated by a matrix"
    )
    plan.add_argument("config", type=Path)
    plan.add_argument(
        "--only",
        action="append",
        default=[],
        type=_parse_filter,
        metavar="KEY=VALUE",
        help="retain matching runs; may be repeated",
    )
    plan.add_argument(
        "--format",
        choices=("table", "json", "yaml"),
        default="table",
        help="output format (default: table)",
    )
    plan.add_argument(
        "--limit",
        type=int,
        default=20,
        help="maximum displayed runs; use 0 for all (default: 20)",
    )
    plan.add_argument(
        "--write-manifests",
        type=Path,
        metavar="DIRECTORY",
        help="write all filtered runs as individual resolved YAML files",
    )
    return parser


def _validate_command(config_path: Path) -> int:
    config = load_experiment(config_path)
    runs = expand_experiment(config)
    print(
        f"Valid configuration: {config.name} "
        f"({len(config.matrices)} matrices, {len(runs)} runs)"
    )
    return 0


def _plan_command(args: argparse.Namespace) -> int:
    if args.limit < 0:
        raise ConfigError("--limit must be zero or a positive integer.")

    config = load_experiment(args.config)
    runs = expand_experiment(config, only=_filters(args.only))
    if not runs:
        raise ConfigError("No runs match the selected filters.")

    displayed = runs if args.limit == 0 else runs[: args.limit]
    print(_serialize(displayed, args.format))
    print(
        f"Showing {len(displayed)} of {len(runs)} resolved runs.",
        file=sys.stderr,
    )

    if args.write_manifests:
        directory = write_run_manifests(runs, args.write_manifests)
        print(f"Wrote {len(runs)} manifests to {directory}.", file=sys.stderr)
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    """Run the command-line interface."""

    parser = _build_parser()
    args = parser.parse_args(argv)
    try:
        if args.command == "validate":
            return _validate_command(args.config)
        if args.command == "plan":
            return _plan_command(args)
        parser.error(f"unknown command: {args.command}")
    except ConfigError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
