"""Command-line interface for experiment validation and planning."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import sys
from typing import Any, Sequence

import yaml

from seismic_byol.environments import (
    CONFIG_ROOT_VARIABLE,
    ENVIRONMENT_VARIABLE,
    load_dataset_registry,
    load_environment,
    resolve_environment_name,
)
from seismic_byol.experiments import (
    ConfigError,
    ResolvedRun,
    expand_experiment,
    load_experiment,
    write_run_manifests,
)
from seismic_byol.materialize import (
    MaterializedRun,
    materialize_experiment,
    write_materialized_manifests,
)


def _parse_filter(raw: str) -> tuple[str, Any]:
    if "=" not in raw:
        raise argparse.ArgumentTypeError("filters must use KEY=VALUE syntax")
    key, raw_value = raw.split("=", 1)
    if not key or not raw_value:
        raise argparse.ArgumentTypeError("filters must use non-empty KEY=VALUE syntax")
    try:
        value = yaml.safe_load(raw_value)
    except yaml.YAMLError as exc:
        raise argparse.ArgumentTypeError(f"invalid filter value: {exc}") from exc
    return key, value


def _filters(items: Sequence[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in items:
        if key in result and result[key] != value:
            raise ConfigError(f"Filter {key!r} was provided with conflicting values.")
        result[key] = value
    return result


def _format_value(value: Any) -> str:
    if isinstance(value, str):
        return value
    return json.dumps(value, sort_keys=True)


def _table(runs: Sequence[ResolvedRun]) -> str:
    if not runs:
        return "No runs match the selected filters."

    axes = sorted({axis for run in runs for axis in run.values})
    headers = ["run_id", "matrix", "stage", *axes]
    rows = [
        [
            run.run_id,
            run.matrix_name,
            run.stage,
            *[_format_value(run.values.get(axis, "-")) for axis in axes],
        ]
        for run in runs
    ]
    widths = [
        max(len(headers[index]), *(len(row[index]) for row in rows))
        for index in range(len(headers))
    ]

    def format_row(row: Sequence[str]) -> str:
        return "  ".join(value.ljust(widths[index]) for index, value in enumerate(row))

    separator = "  ".join("-" * width for width in widths)
    return "\n".join([format_row(headers), separator, *(format_row(row) for row in rows)])


def _serialize(
    runs: Sequence[ResolvedRun] | Sequence[MaterializedRun],
    output_format: str,
) -> str:
    manifests = [run.as_dict() for run in runs]
    if output_format == "json":
        return json.dumps(manifests, indent=2, sort_keys=False)
    if output_format == "yaml":
        return yaml.safe_dump(manifests, sort_keys=False)
    resolved_runs = [
        run.run if isinstance(run, MaterializedRun) else run for run in runs
    ]
    return _table(resolved_runs)


def _add_environment_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--environment",
        help=f"execution profile; overrides {ENVIRONMENT_VARIABLE}",
    )
    parser.add_argument(
        "--check-paths",
        action="store_true",
        help="verify required dataset directories in the selected environment",
    )


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="seismic-byol",
        description="Validate and expand reproducible Seismic BYOL experiment matrices.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    validate = subparsers.add_parser(
        "validate", help="validate a configuration and count its runs"
    )
    validate.add_argument("config", type=Path)
    _add_environment_arguments(validate)

    plan = subparsers.add_parser(
        "plan", help="show the concrete runs generated by a matrix"
    )
    plan.add_argument("config", type=Path)
    plan.add_argument(
        "--only",
        action="append",
        default=[],
        type=_parse_filter,
        metavar="KEY=VALUE",
        help="retain matching runs; may be repeated",
    )
    plan.add_argument(
        "--format",
        choices=("table", "json", "yaml"),
        default="table",
        help="output format (default: table)",
    )
    plan.add_argument(
        "--limit",
        type=int,
        default=20,
        help="maximum displayed runs; use 0 for all (default: 20)",
    )
    plan.add_argument(
        "--write-manifests",
        type=Path,
        metavar="DIRECTORY",
        help="write all filtered runs as individual resolved YAML files",
    )
    _add_environment_arguments(plan)
    return parser


def _config_root(config_path: Path) -> Path:
    override = os.environ.get(CONFIG_ROOT_VARIABLE)
    if override:
        return Path(override)
    resolved = config_path.resolve()
    if resolved.parent.name == "experiments":
        return resolved.parent.parent
    candidate = Path.cwd() / "configs"
    if candidate.is_dir():
        return candidate
    raise ConfigError(
        f"Cannot locate configs directory for {config_path}; set {CONFIG_ROOT_VARIABLE}."
    )


def _runtime(
    config_path: Path,
    environment_name: str | None,
):
    name = resolve_environment_name(environment_name)
    config_root = _config_root(config_path)
    registry = load_dataset_registry(config_root)
    environment = load_environment(name, config_root)
    return environment, registry


def _path_issue_message(materialized_runs: Sequence[MaterializedRun]) -> str | None:
    unique = {
        (issue.dataset, issue.role, str(issue.path), issue.message): issue
        for materialized in materialized_runs
        for issue in materialized.issues
    }
    if not unique:
        return None
    examples = list(unique.values())[:5]
    details = "; ".join(
        f"{issue.dataset}/{issue.role}: {issue.path}" for issue in examples
    )
    remainder = len(unique) - len(examples)
    suffix = f"; and {remainder} more" if remainder else ""
    return f"{len(unique)} required dataset paths are missing: {details}{suffix}"


def _validate_command(args: argparse.Namespace) -> int:
    config = load_experiment(args.config)
    runs = expand_experiment(config)
    environment_name = args.environment or os.environ.get(ENVIRONMENT_VARIABLE)
    environment_suffix = ""
    if environment_name or args.check_paths:
        environment, registry = _runtime(args.config, args.environment)
        materialized = materialize_experiment(
            config,
            environment,
            registry,
            check_paths=args.check_paths,
        )
        issue_message = _path_issue_message(materialized)
        if issue_message:
            raise ConfigError(issue_message)
        environment_suffix = f", environment={environment.name}"

    print(
        f"Valid configuration: {config.name} "
        f"({len(config.matrices)} matrices, {len(runs)} runs{environment_suffix})"
    )
    return 0


def _plan_command(args: argparse.Namespace) -> int:
    if args.limit < 0:
        raise ConfigError("--limit must be zero or a positive integer.")

    config = load_experiment(args.config)
    selected_filters = _filters(args.only)
    runs = expand_experiment(config, only=selected_filters)
    if not runs:
        raise ConfigError("No runs match the selected filters.")

    environment_name = args.environment or os.environ.get(ENVIRONMENT_VARIABLE)
    planned: Sequence[ResolvedRun] | Sequence[MaterializedRun] = runs
    if environment_name or args.check_paths:
        environment, registry = _runtime(args.config, args.environment)
        materialized = materialize_experiment(
            config,
            environment,
            registry,
            only=selected_filters,
            check_paths=args.check_paths,
        )
        issue_message = _path_issue_message(materialized)
        if issue_message:
            raise ConfigError(issue_message)
        planned = materialized

    displayed = planned if args.limit == 0 else planned[: args.limit]
    print(_serialize(displayed, args.format))
    print(
        f"Showing {len(displayed)} of {len(planned)} resolved runs.",
        file=sys.stderr,
    )

    if args.write_manifests:
        if planned and isinstance(planned[0], MaterializedRun):
            directory = write_materialized_manifests(planned, args.write_manifests)
        else:
            directory = write_run_manifests(planned, args.write_manifests)
        print(f"Wrote {len(planned)} manifests to {directory}.", file=sys.stderr)
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    """Run the command-line interface."""

    parser = _build_parser()
    args = parser.parse_args(argv)
    try:
        if args.command == "validate":
            return _validate_command(args)
        if args.command == "plan":
            return _plan_command(args)
        parser.error(f"unknown command: {args.command}")
    except ConfigError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
